#!/bin/bash

# TipTap AI - Desktop Launcher Script
# Generated by install.sh – do not edit manually, re-run install.sh instead
#
# This file is a placeholder. Run ./install.sh to generate a version
# with the correct project path for this machine.

echo "Please run ./install.sh first to configure the correct project path."
exit 1
